apiVersion: v2
name: apim
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: microcks
    version: 0.1.0
    repository: file://microcks
  - name: threescale-tenant-secret
    version: 0.1.0
    repository: file://threescale-tenant-secret
  - name: globex-mobile
    version: 0.1.0
    repository: file://globex-mobile
